title: SOMaR Data Format v0.1 (draft) 
description: First draft of the cummunity standard data format conventions for Sensing the Ocean with Marine Radar 
theme: just-the-docs

url: https://sensing-the-ocean-with-marine-radar.github.io/somar-format-draft

aux_links:
  "SOMaR Community": https://github.com/sensing-the-ocean-with-marine-radar
aux_links_new_tab: true
