title: Data Format Conventions for Sensing the Ocean with Marine Radar (SOMaR-data-formats-v0.1-draft) 
description: First Draft of the cummunity standard data format conventions for Sensing the Ocean with Marine Radar 
theme: just-the-docs

url: https://somar-format-draft.github.io

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
